core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    VistaFundacion,
    CheckoutView,
    CheckoutView2,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    VistaFundacionesLista,
    VistaServiciosLista,
    VistaComunicadosLista,
    VistaServicio,
    VistaComunicado,
    VistaRegistrarFundacion,
    VistaHacerComunicado
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('servicios/', VistaServiciosLista.as_view(), name='servicios'),
    path('fundaciones/', VistaFundacionesLista.as_view(), name='fundaciones'),
    path('comunicados/', VistaComunicadosLista.as_view(), name='comunicados'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('checkout2/', CheckoutView2.as_view(), name='checkout2'),
    path('registrarFundacion/', VistaRegistrarFundacion.as_view(),
         name='registrar-fundacion'),
    path('hacerComunicado/', VistaHacerComunicado.as_view(),
         name='hacer-comunicado'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('servicio/<slug>/', VistaServicio.as_view(), name='servicio'),
    path('comunicado/<slug>/', VistaComunicado.as_view(), name='comunicado'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('fundacion/<slug>/', VistaFundacion.as_view(), name='fundacion'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<main>
  <div class="container wow fadeIn">
    <h2 class="my-5 h2 text-center">Checkout form</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body">
            {% csrf_token %}

            <h3>Shipping address</h3>

            <div class='hideable_shipping_form'>

              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address'
                  class='form-control' />
                <label for="shipping_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2'
                  class='form-control' />
                <label for="shipping_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.shipping_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="shipping_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip'
                    class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="same_billing_address"
                  id="same_billing_address">
                <label class="custom-control-label" for="same_billing_address">Billing address is the same as my
                  shipping address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_shipping"
                  id="set_default_shipping">
                <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
              </div>

            </div>

            {% if default_shipping_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
              <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{
                default_shipping_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}

            <hr>

            <h3>Billing address</h3>

            <div class='hideable_billing_form'>
              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address'
                  class='form-control' />
                <label for="billing_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2'
                  class='form-control' />
                <label for="billing_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.billing_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="billing_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>

              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
              </div>

            </div>

            {% if default_billing_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
              <label class="custom-control-label" for="use_default_billing">Use default billing address: {{
                default_billing_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}
            <hr>

            <h3>Payment option</h3>

            <div class="d-block my-3">
              {% for value, name in form.fields.payment_option.choices %}
              <div class="custom-control custom-radio">
                <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                  class="custom-control-input" required>
                <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
              </div>
              {% endfor %}
            </div>

            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

          </form>

        </div>

      </div>

      <div class="col-md-4 mb-4">
        {% include "order_snippet.html" %}
      </div>

    </div>

  </div>
</main>

{% endblock content %}

{% block extra_scripts %}
<script>
  var hideable_shipping_form = $('.hideable_shipping_form');
  var hideable_billing_form = $('.hideable_billing_form');

  var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
  var use_default_billing = document.querySelector("input[name=use_default_billing]");

  use_default_shipping.addEventListener('change', function () {
    if (this.checked) {
      hideable_shipping_form.hide();
    } else {
      hideable_shipping_form.show();
    }
  })

  use_default_billing.addEventListener('change', function () {
    if (this.checked) {
      hideable_billing_form.hide();
    } else {
      hideable_billing_form.show();
    }
  })

</script>
{% endblock extra_scripts %}

templates/crear_fundacion.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<main>
  <div class="container wow fadeIn">
    <h2 class="my-5 h2 text-center">Registra una fundación</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body" enctype="multipart/form-data">
            {% csrf_token %}

            <h3>Información del establecimiento</h3>

            <div class='hideable_shipping_form'>

              <div class="md-form mb-5">
                <h4 class="mb-1">
                  <small class="text-muted">Nombre de la fundación
                  </small>
                </h4>
                <input type='text' placeholder='Ejemplo: Fundación San José Cuervo' id='nombre' name='nombre'
                  class='form-control' required />
              </div>

              <div class="md-form mb-5">
                <h4 class="mb-2">
                  <small class="text-muted">Descripción
                  </small>
                </h4>
                <h5>
                  <small class="text-muted">Danos alguna información acerca de la fundación y sus motivaciones.
                  </small>
                </h5>
                <textarea class="form-control" rows="4" id='descripcion' name='descripcion'
                  placeholder=" Información de la entidad" required></textarea>
              </div>

              <!--Grid column-->
              <h4>
                <small class="text-muted">Identificación administrador</small>
              </h4>
              <div class="form-outline mb-3">
                <div class="form-helper text-muted">Nombre completo de la persona a cargo de la fundación
                  (administrador).</div>
                <input type="text" id="nombre_admin" name="nombre_admin" class="form-control"
                  placeholder='Nombres y apellidos' />
              </div>
              <div class="form-outline mb-5">
                <div class="form-helper text-muted">Digita el número de identificación del administrador sin puntos ni
                  guiones.</div>
                <input type="number" id="cc_admin" name="cc_admin" class="form-control"
                  placeholder='Número de cédula' />
              </div>
              <h4>
                <small class="text-muted">Código NIT</small>
              </h4>
              <div class="form-outline mb-5">
                <div class="form-helper text-muted">El código NIT nos da la certeza de que estás registrando una entidad
                  registrada en la cámara de comercio. Escribe el número de identificación sin puntos, guiones ni
                  dígito
                  de
                  verificación.</div>
                <input type="number" id="codigo_nit" name="codigo_nit" class="form-control"
                  placeholder='Ejemplo: 901097915' />
              </div>
              <h4>
                <small class="text-muted">Número de contacto</small>
              </h4>
              <div class="form-outline mb-5">
                <div class="form-helper text-muted">Proporciona un número para contactar la fundación, no un número
                  personal.</div>
                <input type="number" id="telefono" name="telefono" class="form-control" placeholder='Teléfono' />
              </div>
            </div>

            <h4>
              <small class="text-muted">Departamento</small>
            </h4>
            <h5>
              <small class="text-muted">Selecciona el departamento donde se ubica la entidad.</small>
            </h5>
            <div class="col-lg-4 col-md-12 mb-4">
              <h5>
                <select class="custom-select d-block w-100" name="departamento" id="departamento" required>
                  <option value="">Selecciona...</option>
                  {% for i in form.fields.departamentos_list.choices %}
                  <option>{{i}}</option>
                  {% endfor %}
                </select>
                <div class="invalid-feedback">
                  Selecciona una opción válida.
                </div>

            </div>
            <!--Grid column-->

            <div class="md-form mb-5">
              <h4 class="mb-1">
                <small class="text-muted">Ciudad
                </small>
              </h4>
              <h5>
                <small class="text-muted">Escribe el nombre de la ciudad o municipio.</small>
              </h5>
              <input type='text' placeholder='Tu ciudad' id='ciudad' name='ciudad' class='form-control' required />
            </div>

            <div class="md-form mb-5">
              <h4 class="mb-1">
                <small class="text-muted">Dirección
                </small>
              </h4>
              <input type='text' placeholder='Ejemplo: Carrera 44a Número 17-60' id='direccion' name='direccion'
                class='form-control' required />
            </div>


            <h4>
              <small class="text-muted">Estrato</small>
            </h4>
            <h5>
              <small class="text-muted">Selecciona el estrato del barrio en que está ubicada la fundación.</small>
            </h5>
            <div class="col-lg-4 col-md-12 mb-4">
              <h5>
                <select class="custom-select d-block w-100" name="estrato" id="estrato" required>
                  <option value="">Selecciona...</option>
                  {% for i in form.fields.estratos_list.choices %}
                  <option>{{i}}</option>
                  {% endfor %}
                </select>
                <div class="invalid-feedback">
                  Selecciona una opción válida.
                </div>

            </div>
            <!--Grid column-->

            <div class="mb-5">
              <h4>
                <small class="text-muted">Foto
                </small>
              </h4>
              <h5>
                <small class="text-muted">Selecciona la imagen identificativa de la fundación.</small>
              </h5>
              <input class="form-control" type="file" id="foto" accept="image/*" name="foto" required>
            </div>

            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="terminos" id="terminos" required>
              <label class="custom-control-label text-muted" for="terminos">Acepto términos y condiciones.</label>
            </div>
        </div>
        <hr class="mb-4">
        <button class="btn btn-lg btn-block white-text" type="submit"
          style=" background-color: rgb(63, 44, 78);">Publicar</button>
      </div>



      </form>
      <div class="col-md-4 mb-4">
        {% include "order_snippet.html" %}
      </div>

    </div>


  </div>


  </div>

  </div>
</main>

{% endblock content %}

{% block extra_scripts %}
<script>
  var hideable_shipping_form = $(' .hideable_shipping_form'); var hideable_billing_form = $('.hideable_billing_form');
  var use_default_shipping = document.querySelector("input[name=use_default_shipping]"); var
    use_default_billing = document.querySelector("input[name=use_default_billing]");
  use_default_shipping.addEventListener('change', function () {
    if (this.checked) {
      hideable_shipping_form.hide();
    } else { hideable_shipping_form.show(); }
  })
  use_default_billing.addEventListener('change', function () {
    if (this.checked) {
      hideable_billing_form.hide();
    } else { hideable_billing_form.show(); }
  }) </script>
{% endblock extra_scripts %}

templates/footer.html
<!-- Footer -->
<footer class="bg-light text-center text-black">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-2">
      <!-- Facebook -->
      <i href="/checkout2" class="fab fa-facebook-f mr-3"></i></a>

      <!-- Twitter -->
      <i href="/checkout2" class="fab fa-twitter mr-3"></i></a>

      <!-- Google -->
      <i href="/checkout2" class="fab fa-google mr-3"></i></a>

      <!-- Instagram -->
      <i href="/checkout2" class="fab fa-instagram mr-3"></i></a>

      <!-- Linkedin -->
      <i href="/checkout2" class="fab fa-linkedin-in mr-3"></i></a>

      <!-- Github -->
      <i href="/checkout2" class="fab fa-github mr-3"></i></a>
    </section>
    <!-- Section: Social media -->

    <!-- Section: Text 
    <section class="mb-4">
      <p>
        Give and change a life.
      </p>
    </section>-->
    <!-- Section: Text -->


  </div>
  <!-- Copyright -->
  <!-- <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);"> -->
  <div class="text-center p-3 text-white" style=" background-color: rgb(63, 44, 78);">
    © 2022 Copyright:
    <a class="text-white" href="/">Givesy.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

templates/fundacion.html
{% extends "base.html" %}

{% block content %}
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4 text-center">

        <img src="{{ object.image.url }}" class="img-fluid" alt="" width="300" height="300">>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <p class="lead font-weight-bold text-capitalize">{{ object.nombre }}</p>

          <p>{{ object.descripcion }}</p>

          <h5>
            <strong>
              <span href="{{ item.get_absolute_url }}" class="badge bg-secondary">{{ object.tipo }}</span>
            </strong>
          </h5>

          <p class="text-capitalize">
            <strong class="fw-bolder">Administrador: </strong>
            <a>{{ object.nombre_admin }} </a>
          </p>

          <p class="text-capitalize">
            <strong class="fw-bolder">Cédula: </strong>
            <a>{{ object.cc_admid }} </a>
          </p>

          <p class="text-capitalize">
            <strong class="fw-bolder">Código NIT: </strong>
            <a>{{ object.codigo_nit }} </a>
          </p>
          <p>
          <h6>El código NIT certifica que la página está registrada en la cámara de comercio. Más
            información en
            <a href="http://www.rues.org.co/"> http://www.rues.org.co/</a>
          </h6>
          </p>

          <p class="text-capitalize">
            <strong class="fw-bolder">Departamento: </strong>
            <a>{{ object.departamento }} </a>
          </p>

          <p class="text-capitalize">
            <strong class="fw-bolder">Ciudad: </strong>
            <a>{{ object.ciudad }} </a>
          </p>

          <p class="text-capitalize">
            <strong class="fw-bolder">Dirección: </strong>
            <a>{{ object.direccion }} </a>
          </p>

          <p class="text-capitalize">
            <strong class="fw-bolder">Estrato: </strong>
            <a>{{ object.estrato }} </a>
          </p>

          <h6>
            <strong>
              Contactar <i class="fas fa-phone"></i></strong>
          </h6>

          <p class="text-capitalize">
            <strong class="fw-bolder">Teléfono: </strong>
            <a>{{ object.telefono }} </a>
          </p>

          <p class="">
            <strong class="fw-bolder">Email: </strong>
            <a>{{ object.email }} </a>
          </p>

          {% for i in object.administrador.fundaciones %}
          {% if i == object.idFundacion %}
          <p>Eres administrador. <a href="{{ item.delete_product }}">Eliminar fundación </a></p>
          {% endif %}
          {% endfor %}

          {% comment %} <form class="d-flex justify-content-left">
            <!-- Default input -->
            <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
            <button class="btn btn-primary btn-md my-0 p" type="submit">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>

          </form>
          <a href="/" class="btn btn-success btn-md my-0 p">
            Contactar Fundación
            <i class="fas fa-phone"></i>
          </a> {% endcomment %}
          {% comment %}
          <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
            Añadir a lista de deseos
            <i class="fas fa-list-ul ml-1"></i>
          </a>

          <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p md-3">
            Remove from cart
          </a> {% endcomment %}

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->


    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Additional information</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>

{% endblock content %}

templates/navbar.html
{% load static %}
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand" href="/">
      <img src="{% static '/images/home/finallogo5.png' %}" alt="Givesy" width="149" height="40"
        class="d-inline-block align-text-top">
    </a>

    {% comment %}
    <a class="navbar-brand" href="#">
      <img src="images/home/finallogo.png" height="20" alt="MDB Logo" loading="lazy" />
    </a>

    <a class="navbar-brand waves-effect" href="/">
      <strong class="blue-text">Givesy</strong>
    </a> {% endcomment %}

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        {% comment %} <li class="nav-item active">
          <a class="nav-link waves-effect" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
        </li> {% endcomment %}
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}


        <li class="nav-item md-6">
          <a href="{% url 'core:checkout2' %}" class="nav-link waves-effect">
            <i class="fas fa-hands-helping"></i>
            <span class="clearfix d-none d-sm-inline-block"> Publicar </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
            <i class="fas fa-list-ul"></i>
            <span class="badge rounded-pill badge-notification bg-secondary">{{ request.user|cart_item_count }}</span>
            <span class="clearfix d-none d-sm-inline-block"> Lista de deseos </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Cerrar sesión </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Iniciar sesión </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Registrarse </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2>Lista de deseos</h2>
            <h4>
                <small class="text-muted">Productos y servicios guardados
                </small>
            </h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Titulo</th>
                        <th scope="col">Ofertante</th>
                        <th scope="col">Tipo</th>
                        <th scope="col">Ciudad</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ order_item.item.idProducto }}</th>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.ofertante }}</td>
                        <td>{{ order_item.item.tipo }}</td>
                        <td>{{ order_item.item.ciudad }}</td>
                        <td>
                            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>

                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Tu lista de deseos está vacía.</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-secondary float-right white-text' href='/'>Volver</a>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>

    </div>
</main>

{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}